name: Python application
on:
  push:                                                    # Trigger = push
    branches: [ "main" ]
jobs:
  job_build-and-test:                                      # Job N° 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10                             # Step N° 1
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Python Dependencies                    # Step N° 2
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Check Syntax with Lint                         # Step N° 3
      run: |
        # stops build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install REST requests to access API            # Step N° 4
      run: |
        python -m pip install -r ./test_api/requirements.txt        
    - name: Run Unit Tests                                 # Step N° 5
      run: |
        # pytest option rAll prints outputs of success and failure tests
        python -m pytest --import-mode=append -rA ./test_api/
    - name: Request Deployment to Staging                  # Step N° 6
      run: |        
        # runs only if all Unit Tests succeeded
        curl -X GET 13.92.86.145:6543/deploy_to_staging/ \
        --no-progress-meter # option to omit progress stats
